#!/bin/sh

{

if [ ${#} -eq 0 ]
then 
  FILENAME=''
else 
  FILENAME=`eval echo '$'{$#}`
fi

COMMAND='cat'
while getopts "f" opt; do
    case $opt in
        f) COMMAND='tail -f'
    esac
done

$COMMAND $FILENAME | \
sed -e s/./うんこ/g

}
